admins/urls.py
from django.conf.urls import url

from admins import views

urlpattern = [
    url(r'^home/$',views.home,name='home'),
    url(r'^$',views.index,name='index'),
    url(r'^upload/products/$',views.uploadproducts,name='uploadproducts'),
    url(r'^charts/Multivendor-Analysis/(?P<chart_type>\w+)/$',views.charts,name='charts'),
    url(r'^charts/Knowledge-Based-Opinion/(?P<chart_type>\w+)/$',views.charts1,name='charts1'),
    url(r'^charts/Region-wise-Opinion-Analysis/(?P<chart_type>\w+)/$',views.charts2,name='charts2'),
    url(r'^charts/Sentiment-Wise-Analysis/(?P<chart_type>\w+)/$',views.charts3,name='charts3'),
    url(r'^logout/$',views.logout,name='logout'),
]

css/CHARACTERIZING_AND_PREDICTING/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin

from CHARACTERIZING_AND_PREDICTING import settings

from admins.urls import urlpattern as admin_urlpatterns
from user.urls import urlpattern as users_urlpatterns
from vendor.urls import urlpattern as vendor_urlpatterns


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^admins/',include((admin_urlpatterns,'admins'),namespace='admins'),name='admins'),
    url(r'',include((users_urlpatterns,'user'),namespace='user'),name='user'),
    url(r'^vendor/',include((vendor_urlpatterns,'vendor'),namespace='vendor'),name='vendor'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.conf.urls import url

from user import views

urlpattern = [
    url(r'^$',views.index,name='index'),
    url(r'^registration$',views.registration,name='registration'),
    url(r'^home/$',views.home,name='home'),
    url(r'^Cart/$',views.cart,name='cart'),
    url(r'^View/Ratings/(?P<pk>\d+)/$',views.viewratings,name='ratings'),
    url(r'^Add/Ratings/(?P<pk>\d+)/$',views.addratings,name='addratings'),
    url(r'^view/product/(?P<pk>\d+)/$',views.viewproduct,name='viewproduct'),
    url(r'^logout/$',views.logout,name='logout'),
]

assets/templates/general/general.html
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <style>
    body{
        background-image: url('{% static 'red1.jpg' %}');
        background-repeat: no-repeat;
        background-attachment: fixed;
        background-position: center;
        background-size: cover;
        padding:0px;
        margin:0px;
        }
        .imgg{
        position:fixed;
        padding:0px;
        margin:0px;
        width:100%;
        height:100%;
        background:rgba(0,0,0,0.6);
        }
        .title h2{
        text-align:center;
        padding:10px;
        }
        .headings ul {
        width:100%;
        text-align:center;

        }
        .headings ul li:hover,.headings ul li:hover a{
        background:red;
        color:white;
        }
        .headings ul li a {
        text-decoration:none;
        color:yellow;
        }
        .headings ul li {
        padding:10px;
        text-algin:center;
        border:1px solid white;
        width:20%;
        color:pink;
         background:blue;
    display: inline-block;
}
    </style>
</head>
<body>
    <div class="imgg">
        <div class="title"><h2 style="color:white;">CHARACTERIZING AND PREDICTING EARLY REVIEWERS FOR EFFECTIVE PRODUCT MARKETING ON E-COMMERCE WEBSITES</h2></div>
        {% if request.session.userid %}
            {% if request.session.username == 'admin' %}
            <div class="headings">
                <ul>
                    <li>
                        <a href="{% url 'admins:home' %}" >home</a>
                    </li>
                    <li>
                        <a href="{% url 'admins:uploadproducts' %}">upload products</a>
                    </li>
                    <li>
                        <a href="{% url 'admins:charts' 'all' %}">chart</a>
                    </li>
                    <li>
                        <a href="{% url 'admins:logout' %}">logout</a>
                    </li>
                </ul>
            </div>
            {% else %}
            <div class="headings">
                <ul>
                    <li><a href="{% url 'user:home' %}">home</a></li>
                    <li><a href="{% url 'user:cart' %}">cart</a></li>
                    <li><a href="{% url 'user:logout' %}">logout</a></li>
                </ul>
            </div>
            {% endif %}
        {% endif %}
        {% block mainblock %}
        {% endblock %}
    </div>
</body>
</html>